### PR TITLE
re-add missing url method to live_server

### LINKED ISSUE #140: 'LiveServer' object has no attribute 'url'
**Describe the bug**
When using `live_server` mode, the actual `live_server` fixture cannot be repr'd because of the missing `url` attribute.

This appears to have been broken in e9b8321b3e1051b163ad5342db0aa529e5f7ce9f, which removed the `url()` method

**To Reproduce**
Add `pytest-flask` to a project and attempt to print the `live_server` fixture, as so:

```
import pytest
import flask


@pytest.fixture(scope='session')
def app():
    return flask.Flask('test')

def test_foo(client, live_server):
    print(live_server)
```

**Expected behavior**
Pretty print

**Actual Behavior**
```
self = <[AttributeError("'LiveServer' object has no attribute 'url'") raised in repr()] LiveServer object at 0x7f0c7b63c6a0>

    def __repr__(self):
>       return "<LiveServer listening at %s>" % self.url()
E       AttributeError: 'LiveServer' object has no attribute 'url'
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python Version: all
 - pytest-flask version: 1.2.0

### PR DESCRIPTION
**Pull request by Roguelazer**
Fixes #140. This is a literal copy-paste of the method as it existed prior to v1.2.0 (prior to e9b8321b3e1051b163ad5342db0aa529e5f7ce9f)

### CODE REVIEW

**Review by northernSage — APPROVED** [review]
Thanks!

**Comment by janpeterka** [comment]
Hi, any idea when this fix will be released? Thanks!
