### ISSUE TITLE
'LiveServer' object has no attribute 'url'

### ISSUE THREAD

**Issue by Roguelazer** [pytest-dev/pytest-flask#140]
**Describe the bug**
When using `live_server` mode, the actual `live_server` fixture cannot be repr'd because of the missing `url` attribute.

This appears to have been broken in e9b8321b3e1051b163ad5342db0aa529e5f7ce9f, which removed the `url()` method

**To Reproduce**
Add `pytest-flask` to a project and attempt to print the `live_server` fixture, as so:

```
import pytest
import flask


@pytest.fixture(scope='session')
def app():
    return flask.Flask('test')

def test_foo(client, live_server):
    print(live_server)
```

**Expected behavior**
Pretty print

**Actual Behavior**
```
self = <[AttributeError("'LiveServer' object has no attribute 'url'") raised in repr()] LiveServer object at 0x7f0c7b63c6a0>

    def __repr__(self):
>       return "<LiveServer listening at %s>" % self.url()
E       AttributeError: 'LiveServer' object has no attribute 'url'
```

**Environment (please complete the following information):**
 - OS: Linux
 - Python Version: all
 - pytest-flask version: 1.2.0

**Comment by northernSage** [comment]
Yep, that was definitely an accident and shouldn't have been removed. Thanks for spotting it and taking the time to open the PR/issue @Roguelazer !

**Comment by victor9000** [comment]
For those needing a working version, you can use pytest-flask==1.1.0

@northernSage Does it make sense to use something like flake8 to avoid bugs like this in the future?  Otherwise, any other form of static analysis can be useful for identifying missing functions.

**Comment by northernSage** [comment]
flake8 with bugbear has already been added using [pre-commits](https://github.com/pytest-dev/pytest-flask/blob/master/.pre-commit-config.yaml). A better alternative would be to extend test coverage to 100%. 

This is what our coverage current looks like:

> pytest_flask/__init__.py---------------100%
> pytest_flask/_internal.py-------------100%
> pytest_flask/_version.py------------- 100%
> pytest_flask/fixtures.py-------------- 100%
> pytest_flask/live_server.py ---------- 98%
> pytest_flask/plugin.py--------------- 100%
> pytest_flask/pytest_compat.py------ 100%
> Total-----------------------------------99%

This is not bad at all. Giving our high coverage I believe any breaking changes are highly unlikely. This problem only took place because the changes that caused the problem happened in the same [PR](https://github.com/pytest-dev/pytest-flask/pull/133) where I extended the test suite so it didn't catch the problem.

I would gladly review a PR to improve the current test suite, but I'll not work on this now for lack of time.
